from ..hex_rt_infrastructure import RTGuardRing, RTTraceRoute, RTPhaseChangeThermalInterface
from .hex_rt_heatsink import RTVaporChamberHeatsink

class HexNativeVariablePSU:
    """
    Native Hexadecimal Variable Power Supply (PSU-HX).
    Steps down raw intake power into ultra-clean, mathematically 
    perfect 0.0625V analog intervals. Features a programmable dial 
    to dynamically scale the motherboard logic voltage.
    """
    def __init__(self, max_amperage=150.0):
        # 16-State Translation Dictionary
        self.hex_states = {
            '0': 0.0000, '1': 0.0625, '2': 0.1250, '3': 0.1875,
            '4': 0.2500, '5': 0.3125, '6': 0.3750, '7': 0.4375,
            '8': 0.5000, '9': 0.5625, 'A': 0.6250, 'B': 0.6875,
            'C': 0.7500, 'D': 0.8125, 'E': 0.8750, 'F': 1.0000
        }
        
        self.max_amps = max_amperage
        self.current_hex_state = 'F'
        self.output_voltage = self.hex_states['F']
        
        # Power delivery requires the thickest copper allowed by RT standards
        self.master_power_bus = RTTraceRoute(copper_oz=3.0, trace_width_mm=10.0, length_mm=30.0)
        
        # Massive EMI protection to scrub the incoming dirty power
        self.rt_guard_ring = RTGuardRing()
        
        # PSU VRMs (Voltage Regulator Modules) get hotter than the CPU
        self.rt_thermal_pad = RTPhaseChangeThermalInterface()
        self.rt_vapor_chamber = RTVaporChamberHeatsink(thermal_capacity_watts=600.0)
        self.vrm_temp_c = 40.0

    def set_system_logic_level(self, target_hex_char):
        """
        Dynamically adjusts the baseline logic voltage for the entire system.
        Allows down-clocking the analog matrix for thermal/stealth management.
        """
        target = str(target_hex_char).upper()
        if target in self.hex_states:
            self.current_hex_state = target
            self.output_voltage = self.hex_states[target]
            print(f"\n[PSU-HX] Logic dial shifted. Master Output calibrated to Hex {self.current_hex_state} ({self.output_voltage}V).")
            return True
        else:
            print(f"[PSU-HX] FAULT: Invalid Hex state '{target_hex_char}'. Keeping current voltage.")
            return False

    def deliver_power(self, requested_amps):
        """
        Outputs clean, Guard-Ring scrubbed power to the motherboard.
        Calculates the massive thermal load generated by stepping down raw power.
        """
        if requested_amps > self.max_amps:
            print(f"[PSU-HX] OCP (Over-Current Protection) TRIPPED. Requested {requested_amps}A exceeds {self.max_amps}A limit.")
            return None

        # 1. Scrub the outgoing logic level
        clean_voltage = self.rt_guard_ring.isolate_logic_stream([self.output_voltage])[0]
        
        # 2. Push it through the 3oz copper master bus
        safe_stream, trace_heat_w = self.master_power_bus.transmit_analog_signal(current_amps=requested_amps, voltage_stream=[clean_voltage])
        
        if not safe_stream:
            print("[PSU-HX] CATASTROPHIC TRACE FAILURE. Master bus impedance bottleneck.")
            return None
            
        # 3. Calculate VRM Thermal Conversion Loss (Assuming 90% efficiency)
        # Power = Voltage * Amps. 10% of that is lost purely as heat during step-down.
        total_power_watts = self.output_voltage * requested_amps
        vrm_heat_w = total_power_watts * 0.10 
        combined_heat = trace_heat_w + vrm_heat_w
        
        # 4. Execute PSU Thermal Cycle
        self.vrm_temp_c += (combined_heat * 0.2)
        self.vrm_temp_c = self.rt_thermal_pad.dissipate_heat(self.vrm_temp_c, combined_heat)
        self.vrm_temp_c = self.rt_vapor_chamber.execute_capillary_cycle(combined_heat, self.vrm_temp_c)
        
        print(f"[PSU-HX] Delivering {requested_amps}A @ {clean_voltage}V ({total_power_watts:.1f}W load). VRM stabilized at {self.vrm_temp_c:.1f}°C.")
        return clean_voltage
